enable-module-update = false
parallel-jobs = 1
compression-level = 9
remove-rv-integrations-checks = false

[Music-anddea]
enabled = false
app-name = "Music"
patches-source = "anddea/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = "latest"
cli-version = "dev"
rv-brand = "ReVanced Anddea"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
arch = "arm64-v8a"
patcher-args = """\
    --striplibs arm64-v8a \
    """
included-patches = ""
excluded-patches = """\
    'Custom branding name for YouTube Music' \
    'Custom branding icon for YouTube Music' \
    """

[YouTube-anddea]
enabled = false
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = "latest"
cli-version = "dev"
rv-brand = "ReVanced Anddea"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
patcher-args = """\
    --striplibs arm64-v8a \
    """
included-patches = ""
excluded-patches = """\
    'Custom branding name for YouTube' \
    'Custom branding icon for YouTube' \
    """

[Music-anddea-dev]
enabled = false
app-name = "Music"
patches-source = "anddea/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = "dev"
cli-version = "dev"
rv-brand = "ReVanced Anddea-dev"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
arch = "arm64-v8a"
patcher-args = """\
    --striplibs arm64-v8a \
    """
included-patches = ""
excluded-patches = """\
    'Custom branding name for YouTube Music' \
    'Custom branding icon for YouTube Music' \
    """

[YouTube-anddea-dev]
enabled = false
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = "dev"
cli-version = "dev"
rv-brand = "ReVanced Anddea-dev"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
patcher-args = """\
    --striplibs arm64-v8a \
    """
included-patches = ""
excluded-patches = """\
    'Custom branding name for YouTube' \
    'Custom branding icon for YouTube' \
    """

[Music-Morphe]
app-name = "Music"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = "latest"
cli-version = "dev"
rv-brand = "Morphe"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
arch = "arm64-v8a"
patcher-args = """\
    --striplibs arm64-v8a \
    """
included-patches = ""
excluded-patches = """\
    'Custom branding' \
    """

[YouTube-Morphe]
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = "latest"
cli-version = "dev"
rv-brand = "Morphe"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
patcher-args = """\
    --striplibs arm64-v8a \
    """
included-patches = ""
excluded-patches = """\
    'Custom branding' \
    """

[Music-Morphe-dev]
app-name = "Music"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = "dev"
cli-version = "dev"
rv-brand = "Morphe-dev"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
arch = "arm64-v8a"
patcher-args = """\
    --striplibs arm64-v8a \
    """
included-patches = ""
excluded-patches = """\
    'Custom branding' \
    """

[YouTube-Morphe-dev]
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = "dev"
cli-version = "dev"
rv-brand = "Morphe-dev"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
patcher-args = """\
    --striplibs arm64-v8a \
    """
included-patches = ""
excluded-patches = """\
    'Custom branding' \
    """
